### ISSUE TITLE
Client Info

### ISSUE THREAD

**Issue by ramlaxmi** [ramlaxmi/seyon-gw#1]
NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,PIN_CODE,PHONEPrimary,PHONESecondary, FaxNo, PAN, GSTN, ServiceTaxRegNo(stale), AccountingType,LogoIMg,SignatureImg,Email,BANK_NAME,BANK_ACCT_NUMBER,IFSC_CODE,BRANCH,ACCOUNT_TYPE,SWIFT_CODE,

**Comment by bbroko** [comment]
Completed
